
export const SET_POSITION = 'SET_POSITION'
export const SAVE_PAGE = 'SAVE_PAGE'
export const SET_LOCATION = 'SET_LOCATION'
export const SET_LOCATIONCITY = 'SET_LOCATIONCITY'
export const SET_SEARCHKEY = 'SET_SEARCHKEY'
